try {
  
  //No ERROR thrown!
  
} 
catch (e) {
  
  console.log( e );
  
}
finally {
  
  console.log("Finally done.");
  
}